(function(){
    
    window.vocabulary = {

        TasksAdnAnswers: [
            {
                id:`0`,
                question:`Это интересно, потому что студенты изучают робототехнику, а также изучают компьютерное программирование.`,
                answer:`Es entretenido porque los estudiantes aprenden robótica y también aprenden programación de computadora. `,
                additional:``,
            }, 
            {
                id:`1`,
                question:`Конкурс направлен на поощрение проектов новых профессионалов в области программирования и информационных технологий.`,
                answer:`El concurso quiere incentivar proyectos de nuevos profesionales del área de programación y de Tecnología de la Información.`,
                additional:``,
            }, 
            {
                id:`2`,
                question:`В моей области, как программиста, трех лет было бы достаточно, так как циклы в этих типах продуктов еще короче.`,
                answer:`En mi campo, como programador informático, tres años bastarían, ya que los ciclos en este tipo de productos son aún más reducidos.`,
                additional:``,
            },
        ],

        AddWords: [
            `programa`,
            `línea`,
            `ciencia`,
            `error`,
            `encapsulación`,
            `farol`, 
            `contraseña`, 
            `corchetes`, 
            `gratitud`, 
            `lección`, 
            `código`, 
            `moneda`, 
            `dificultad`, 
            `tú`, 
            `yo`, 
            `ellos`,
            `eso`, 
            `nivel`, 
            `de`, 
            `ellos`, 
            `ella`, 
            `él`, 
            `por`, 
            `qué`, 
            `curva`, 
            `infierno`, 
            `igualdad`, 
            `tipo`, 
            `variable`, 
            `dígito`, 
            `cálculo`,
            `brecha`, 
            `pregunta`, 
            `él`, 
            `alumno`, 
            `estudiante`, 
            `aprendizaje`, 
            `memoria`, 
            `ejemplo`, 
            `estado`, 
            `de`,
            `ánimo`, 
            `gerente`,
            `proyecto`, 
            `límite`,
            `tiempo`, 
            `segundo`, 
            `reloj`,
            ],

    };

})();