"use strict";

(function(){
    
    window.vocabulary = {

        Tasks: [
            {
                Id:`1`,
                Russian:`Это интересно, потому что студенты изучают робототехнику, а также изучают компьютерное программирование.`,
                Spanish:`Es entretenido porque los estudiantes aprenden robótica y también aprenden programación de computadora.`,
                English: `It is entertaining because students learn robotics and also learn computer programming.`,
                Additional:``,
            }, 
            {
                Id:`2`,
                Russian:`Конкурс направлен на поощрение проектов новых профессионалов в области программирования и информационных технологий.`,
                Spanish:`El concurso quiere incentivar proyectos de nuevos profesionales del área de programación y de Tecnología de la Información.`,
                English: `The contest wants to encourage projects of new professionals in the area of programming and Information Technology.`,
                Additional:``,
            }, 
            {
                Id:`3`,
                Russian:`В моей области, как программиста, трех лет было бы достаточно, так как циклы в этих типах продуктов еще короче.`,
                Spanish:`En mi campo, como programador informático, tres años bastarían, ya que los ciclos en este tipo de productos son aún más reducidos.`,
                English: `In my field, as a computer programmer, three years would be enough, since the cycles in these types of products are even shorter.`,
                Additional:``,
            },
            {
                Id:`4`,
                Russian:`Работа консультанта по интернет-технологиям значительно повысила эффективность нашей деятельности.`,
                Spanish:`El trabajo de consultor de tecnologías de Internet ha generado enormes eficiencias en nuestras operaciones.`,
                English: `The work of  internet technologies consultant has created huge efficiencies in our operations.`,
                Additional:``,
            },
            {
                Id:`5`,
                Russian:`Я профессионально работаю веб-программистом, хотя должен сказать, что не являюсь экспертом в дизайне.`,
                Spanish:`Trabajo profesionalmente como programador web aunque debo decir que no soy un experto en diseño.`,
                English: `I am professionally work as a web programmer although I must say that I am not an expert in design.`,
                Additional:``,
            },
            {
                Id:`6`,
                Russian:`Как старший веб-программист я координировал работу небольшой команды графических дизайнеров и HTML-кодеров.`,
                Spanish:`Como programador web senior, coordiné un pequeño equipo de diseñadores gráficos y codificadores HTML.`,
                English: `As Senior Web Programmer I co-ordinated a small team of graphics designers and HTML coders.`,
                Additional:``,
            },
            {
                Id:`7`,
                Russian:`Это веб-приложение, которое позволяет вам управлять всеми вашими установками из Интернета.`,
                Spanish:`Es una aplicación web que te permite gestionar todas tus instalaciones desde la web.`,
                English: `It is a web application that allows you to manage all your installations from the web.`,
                Additional:``,
            },
            {
                Id:`8`,
                Russian:`Этот курс рассматривает структуры данных и алгоритмы в информатике.`,
                Spanish:`Este curso trata las estructuras de datos y los algoritmos en informática.`,
                English: `This course treats data structures and algorithms in computer science.`,
                Additional:``,
            },
            {
                Id:`9`,
                Russian:`Данные космической науки представляют собой значительные долгосрочные инвестиции.`,
                Spanish:`Los datos de la ciencia espacial representan una inversión significativa a largo plazo.`,
                English: `Space science data represent a significant long-term investment.`,
                Additional:``,
            },
            {
                Id:`10`,
                Russian:`Поскольку он избегает облаков точек, чем больше инженер сканирует, тем точнее становится сбор данных.`,
                Spanish:`Debido a que evita las nubes de puntos, cuanto más escanea el ingeniero, más precisa se vuelve la adquisición de datos.`,
                English: `Because it avoids point clouds, the more the engineer scans, the more accurate the data acquisition becomes.`,
                Additional:``,
            },
            // {
            //     Id:`11`,
            //     Russian:``,
            //     Spanish:``,
            //     English: ``,
            //     Additional:``,
            // },        
                
        ],

        AddWords: {

            Spanish: [

                `programa`,
                `línea`,
                `ciencia`,
                `error`,
                `encapsulación`,
                `farol`, 
                `contraseña`, 
                `corchetes`, 
                `gratitud`, 
                `lección`, 
                `código`, 
                `moneda`, 
                `dificultad`, 
                `tú`, 
                `yo`, 
                `ellos`,
                `eso`, 
                `nivel`, 
                `de`, 
                `ellos`, 
                `ella`, 
                `él`, 
                `por`, 
                `qué`, 
                `curva`, 
                `infierno`, 
                `igualdad`, 
                `tipo`, 
                `variable`, 
                `dígito`, 
                `cálculo`,
                `brecha`, 
                `pregunta`, 
                `él`, 
                `alumno`, 
                `estudiante`, 
                `aprendizaje`, 
                `memoria`, 
                `ejemplo`, 
                `estado`, 
                `de`,
                `ánimo`, 
                `gerente`,
                `proyecto`, 
                `límite`,
                `tiempo`, 
                `segundo`, 
                `reloj`,
                ],

            English: [

                `program`,
                `line`,
                `science`,
                `Error`,
                `Encapsulation`,
                `lantern`,
                `password`,
                `brackets`,
                `gratitude`,
                `lesson`,
                `code`,
                `currency`,
                `difficulty`,
                `you`,
                `I`,
                'They',
                `It`,
                `level`,
                `of`,
                'They',
                `She`,
                `he`,
                `by`,
                `what`,
                `curve`,
                `Hell`,
                `Equality`,
                `type`,
                `variable`,
                `digit`,
                `calculation`,
                `gap`,
                `question`,
                `he`,
                `Student`,
                `Student`,
                `Learning`,
                `memory`,
                `Example`,
                `State`,
                `of`,
                `cheer`,
                `manager`,
                `project`,
                `limit`,
                `time`,
                `second`,
                `clock`,
            ],

            Russian: [

                `программа`,
                `линия`,
                `наука`,
                `ошибка`,
                `инкапсуляция`,
                `фонарь`,
                `пароль`,
                `скобки`,
                `благодарность`,
                `урок`,
                `код`,
                `валюта`,
                `трудность`,
                `ты`,
                `я`,
                'Oни',
                `Это`,
                `уровень`,
                `от`,
                `Oни`,
                `Она`,
                `он`,
                `через`,
                `что`,
                `кривая`,
                `добавить`,
                `Равенство`,
                `тип`,
                `переменная`,
                `цифра`,
                `расчет`,
                `пробел`,
                `вопрос`,
                `он`,
                `Студент`,
                `Студент`,
                `Обучение`,
                `память`,
                `Пример`,
                `Состояние`,
                `Из`,
                `развернуть`,
                `менеджер`,
                `проект`,
                `предел`,
                `время`,
                `второй`,
                `часы`,
            ],

        } 

    };

})();