"use strict";

(function(){
    
    window.vocabulary = {

        Tasks: [
            {
                Id:`1`,
                Russian:`Это интересно, потому что студенты изучают робототехнику, а также изучают компьютерное программирование.`,
                Spanish:`Es entretenido porque los estudiantes aprenden robótica y también aprenden programación de computadora.`,
                English: `It is entertaining because students learn robotics and also learn computer programming.`,
                Additional:``,
            }, 
            {
                Id:`2`,
                Russian:`Конкурс направлен на поощрение проектов новых профессионалов в области программирования и информационных технологий.`,
                Spanish:`El concurso quiere incentivar proyectos de nuevos profesionales del área de programación y de Tecnología de la Información.`,
                English: `The contest wants to encourage projects of new professionals in the area of programming and Information Technology.`,
                Additional:``,
            }, 
            {
                Id:`3`,
                Russian:`В моей области, как программиста, трех лет было бы достаточно, так как циклы в этих типах продуктов еще короче.`,
                Spanish:`En mi campo, como programador informático, tres años bastarían, ya que los ciclos en este tipo de productos son aún más reducidos.`,
                English: `In my field, as a computer programmer, three years would be enough, since the cycles in these types of products are even shorter.`,
                Additional:``,
            },
            {
                Id:`4`,
                Russian:`Работа консультанта по интернет-технологиям значительно повысила эффективность нашей деятельности.`,
                Spanish:`El trabajo de consultor de tecnologías de Internet ha generado enormes eficiencias en nuestras operaciones.`,
                English: `The work of  internet technologies consultant has created huge efficiencies in our operations.`,
                Additional:``,
            },
            {
                Id:`5`,
                Russian:`Я профессионально работаю веб-программистом, хотя должен сказать, что не являюсь экспертом в дизайне.`,
                Spanish:`Trabajo profesionalmente como programador web aunque debo decir que no soy un experto en diseño.`,
                English: `I am professionally work as a web programmer although I must say that I am not an expert in design.`,
                Additional:``,
            },
            {
                Id:`6`,
                Russian:`Как старший веб-программист я координировал работу небольшой команды графических дизайнеров и HTML-кодеров.`,
                Spanish:`Como programador web senior, coordiné un pequeño equipo de diseñadores gráficos y codificadores HTML.`,
                English: `As Senior Web Programmer I co-ordinated a small team of graphics designers and HTML coders.`,
                Additional:``,
            },
            {
                Id:`7`,
                Russian:`Это веб-приложение, которое позволяет вам управлять всеми вашими установками из Интернета.`,
                Spanish:`Es una aplicación web que te permite gestionar todas tus instalaciones desde la web.`,
                English: `It is a web application that allows you to manage all your installations from the web.`,
                Additional:``,
            },
            {
                Id:`8`,
                Russian:`Этот курс рассматривает структуры данных и алгоритмы в информатике.`,
                Spanish:`Este curso trata las estructuras de datos y los algoritmos en informática.`,
                English: `This course treats data structures and algorithms in computer science.`,
                Additional:``,
            },
            {
                Id:`9`,
                Russian:`Данные космической науки представляют собой значительные долгосрочные инвестиции.`,
                Spanish:`Los datos de la ciencia espacial representan una inversión significativa a largo plazo.`,
                English: `Space science data represent a significant long-term investment.`,
                Additional:``,
            },
            {
                Id:`10`,
                Russian:`Поскольку он избегает облаков точек, чем больше инженер сканирует, тем точнее становится сбор данных.`,
                Spanish:`Debido a que evita las nubes de puntos, cuanto más escanea el ingeniero, más precisa se vuelve la adquisición de datos.`,
                English: `Because it avoids point clouds, the more the engineer scans, the more accurate the data acquisition becomes.`,
                Additional:``,
            },
            // {
            //     Id:`11`,
            //     Russian:``,
            //     Spanish:``,
            //     English: ``,
            //     Additional:``,
            // },        
                
        ],

        AddWords: {

            Spanish: [

                `777programa`,
                `777línea`,
                `777ciencia`,
                `777error`,
                `777encapsulación`,
                `777farol`, 
                `777contraseña`, 
                `777corchetes`, 
                `777gratitud`, 
                `777lección`, 
                `777código`, 
                `777moneda`, 
                `777dificultad`, 
                `777tú`, 
                `777yo`, 
                `777ellos`,
                `777eso`, 
                `777nivel`, 
                `777de`, 
                `777ellos`, 
                `777ella`, 
                `777él`, 
                `777por`, 
                `777qué`, 
                `777curva`, 
                `777infierno`, 
                `777igualdad`, 
                `777tipo`, 
                `777variable`, 
                `777dígito`, 
                `777cálculo`,
                `777brecha`, 
                `777pregunta`, 
                `777él`, 
                `777alumno`, 
                `777estudiante`, 
                `777aprendizaje`, 
                `777memoria`, 
                `777ejemplo`, 
                `777estado`, 
                `777de`,
                `777ánimo`, 
                `777gerente`,
                `777proyecto`, 
                `777límite`,
                `777tiempo`, 
                `777segundo`, 
                `777reloj`,
                ],

            English: [

                `777program`,
                `777line`,
                `777science`,
                `777Error`,
                `777Encapsulation`,
                `777lantern`,
                `777password`,
                `777brackets`,
                `777gratitude`,
                `777lesson`,
                `777code`,
                `777currency`,
                `777difficulty`,
                `777you`,
                `777I`,
                '777They',
                `777It`,
                `777level`,
                `777of`,
                '777They',
                `777She`,
                `777he`,
                `777by`,
                `777what`,
                `777curve`,
                `777Hell`,
                `777Equality`,
                `777type`,
                `777variable`,
                `777digit`,
                `777calculation`,
                `777gap`,
                `777question`,
                `777he`,
                `777Student`,
                `777Student`,
                `777Learning`,
                `777memory`,
                `777Example`,
                `777State`,
                `777of`,
                `777cheer`,
                `777manager`,
                `777project`,
                `777limit`,
                `777time`,
                `777second`,
                `777clock`,
            ],

            Russian: [

                `777программа`,
                `777линия`,
                `777наука`,
                `777ошибка`,
                `777инкапсуляция`,
                `777фонарь`,
                `777пароль`,
                `777скобки`,
                `777благодарность`,
                `777урок`,
                `777код`,
                `777валюта`,
                `777трудность`,
                `777ты`,
                `777я`,
                '777Oни',
                `777Это`,
                `777уровень`,
                `777от`,
                `777Oни`,
                `777Она`,
                `777он`,
                `777через`,
                `777что`,
                `777кривая`,
                `777добавить`,
                `777Равенство`,
                `777тип`,
                `777переменная`,
                `777цифра`,
                `777расчет`,
                `777пробел`,
                `777вопрос`,
                `777он`,
                `777Студент`,
                `777Студент`,
                `777Обучение`,
                `777память`,
                `777Пример`,
                `777Состояние`,
                `777Из`,
                `777развернуть`,
                `777менеджер`,
                `777проект`,
                `777предел`,
                `777время`,
                `777второй`,
                `777часы`,
            ],

        } 

    };

})();